spring.application.name=antigravity-backend
server.port=8080

de.flapdoodle.mongodb.embedded.version=6.0.4
server.port=8080



# JWT Configuration
jwt.secret=${JWT_SECRET:87c4f4a3e9c12b7a9deaf82c41151a7e2b1d31a5c68d4a9f98c8e14b2d5a3c9e}
jwt.expiration=86400000
